baseURL = 'https://jessejes.com'
languageCode = 'en-us'
title = 'jessejes'
theme = "hugo-papermod-custom"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blogs"
